- name: Creates a notification for the monitors
  lucasheld.uptime_kuma.notification:
    api_url: http://127.0.0.1:3001
    api_username: "{{ kuma_username }}"
    api_password: "{{ kuma_password }}"
    name: down
    state: present
    type: slack
    slackchannel: uptime-kuma-test
    slackchannelnotify: yes
    applyExisting: yes
    slackwebhookURL:  #paste here your slack webhook URL
